### ISSUE TITLE
Bullet alignment and line height inconsistent with iA W

### ISSUE THREAD

**Issue by jkmaxwell** [rcvd/logseq-quattro-theme#2]
First, THANK YOU for doing this theme. That's the most important part.

Second, I'm experiencing decorator bullet alignment issues on all header and larger font blocks. The • decorators and line heights are off. So while the color palette and typeface port is superb, there's a loss of vertical alignment and rhythm that makes the experience negative.

@perezd was able to fix the decorator alignment with 

```
.items-baseline {
    align-items: self-end;
}
```
<img width="507" alt="Sebastián_Ortega" src="https://user-images.githubusercontent.com/342903/147713579-2d293207-07fa-479f-a53f-24b34a26cc90.png">

But the vertical spacing and "large dot" thing is going to take some more work

**Comment by rcvd** [comment]
This idea does not work well with multi-line blocks.
