### ISSUE TITLE
Sidebar, scrollbar css updates for Logseq Version 0.5.9

### ISSUE THREAD

**Issue by Ness-alt** [rcvd/logseq-quattro-theme#5]
default colors coming through on Logseq Version 0.5.9. Scrollbar color, background area for 'new page' button.

<img width="879" alt="Screen Shot 2022-01-22 at 2 01 16 PM" src="https://user-images.githubusercontent.com/73702173/150651919-120ac4ca-0561-44a6-8439-7d2ba8b39a14.png">

Background for 'new page' button is correct when application width is <645 px

Love this theme -- thanks so much for your hard work!!!

**Comment by rcvd** [comment]
Should be fixed
